name: Lint with Hadolint
on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'
  push:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - name: Lint
        run: |
          echo "::add-matcher::.github/hadolint-matcher.json"
          make lint-docker
          echo "::remove-matcher owner=hadolint::"
